package slack

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/slack-go/slack"
)

const (
	ColorDanger  = "#d50000"
	ColorWarning = "#ffab00"
	ColorGood    = "#00c853"
	ColorInfo    = "#2962ff"
)

// createMessageBlock generates a rich message block for Slack.
func createMessageBlock(color, title, details string) slack.MsgOption {
	return slack.MsgOptionAttachments(slack.Attachment{
		Color:      color,
		Fallback:   fmt.Sprintf("%s: %s", title, details),
		AuthorName: "Auto-Irrigation System",
		Title:      title,
		Text:       details,
		Footer:     "Generated by Golang Scheduler",
		Ts:         json.Number(fmt.Sprintf("%d", time.Now().Unix())),
	})
}

// NewErrorMessage creates a new error message block.
func NewErrorMessage(title, details string) slack.MsgOption {
	return createMessageBlock(ColorDanger, title, details)
}

// NewSuccessMessage creates a new success message block.
func NewSuccessMessage(title, details string) slack.MsgOption {
	return createMessageBlock(ColorGood, title, details)
}

// NewInfoMessage creates a new info message block.
func NewInfoMessage(title, details string) slack.MsgOption {
	return createMessageBlock(ColorInfo, title, details)
}
