services:
  auto-irrigation-system-local:
    build:
      context: ..
      dockerfile: Dockerfile
    image: auto-irrigation-system-local
    container_name: auto-irrigation-system-local
    ports:
      - "3100:8080"
    restart: unless-stopped
    env_file:
      - ../.env.local
