name: Build and Deploy Production

on:
  push:
    branches:
      - feature/vibe-code
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: production
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Go dependencies
        run: go get github.com/joho/godotenv

      - name: Create .env file for production
        run: |
          {
            echo "APP_ENV=production"

            # MQTT Configuration
            echo "MQTT_BROKER=${{ vars.MQTT_BROKER }}"
            echo "MQTT_CLIENT_ID=${{ vars.MQTT_CLIENT_ID }}"
            echo "MQTT_USERNAME=${{ secrets.MQTT_USERNAME }}"
            echo "MQTT_PASSWORD=${{ secrets.MQTT_PASSWORD }}"

            # Database Configuration
            echo "DB_HOST=${{ vars.DB_HOST }}"
            echo "DB_PORT=${{ vars.DB_PORT }}"
            echo "DB_SSLMODE=${{ vars.DB_SSLMODE }}"

            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}"
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}"
            echo "POSTGRES_DB=${{ vars.POSTGRES_DB }}"

            # Slack Configuration
            echo "SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}"
            echo "SLACK_SIGNING_SECRET=${{ secrets.SLACK_SIGNING_SECRET }}"
            echo "SLACK_CHANNEL_ID=${{ vars.SLACK_CHANNEL_ID }}"


            echo "DEVICE_CONFIG_PATH=${{ vars.DEVICE_CONFIG_PATH }}" 

          } > .env.production

      - name: Build and deploy application
        env:
          APP_ENV: production
        run: bash ./scripts/update-docker.sh
